default:
    image: maven:3-jdk-11
    tags:
        - docker

stages:
    - test
    - visualize_coverage
    - upload_javadoc

variables:
    MAVEN_CLI_OPTS: "-B --errors --fail-fast"
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2
     -Dmaven.repo.local=.m2/repository
     -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
     -Dorg.slf4j.simpleLogger.showDateTime=true
     -Djava.awt.headless=true"

cache:
    paths:
        - .m2/repository/
        - target/
        - docs/

# Run unit tests and generate test coverage reports
# At this stage all unit tests are run against Wiremock instance
# which imitates live Loadero API
unit_tests:
    stage: test
    script:
        - mvn $MAVEN_CLI_OPTS clean test
        - cat target/site/jacoco/index.html
    artifacts:
        when: always
        paths:
            - target/site/jacoco/jacoco.xml
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml    
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
          allow_failure: true

# Convert JaCoCo test coverage reports into Cobertura format and visualize        
# source: https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html#maven-example
visualize_tests:
    stage: visualize_coverage
    image: haynes/jacoco2cobertura:1.0.4
    script:
        - 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml'
        - 'python /opt/source2filename.py target/site/cobertura.xml'
    needs: ["unit_tests"]
    dependencies:
        - unit_tests
    artifacts:
        reports:
            cobertura: target/site/cobertura.xml

upload_javadoc:
    image: ubuntu
    stage: upload_javadoc
    artifacts:
        when: on_success
        paths:
            - target/site/apidocs/
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
          allow_failure: true
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - apt install sshpass
        - eval $(ssh-agent -s)
    script:
        - sshpass -p $VM_PASS scp -P 22 -o StrictHostKeyChecking=no -r target/site/apidocs/* $SERVER_NAME@$SERVER_IP:/home/$SERVER_NAME/tmp/
        - sshpass -p $VM_PASS ssh -vvv -p22 -o StrictHostKeyChecking=no $SERVER_NAME@$SERVER_IP "echo $VM_PASS | sudo -S -k rm -rf /var/www/apidocs/*"
        - sshpass -p $VM_PASS ssh -p22 -o StrictHostKeyChecking=no $SERVER_NAME@$SERVER_IP "echo $VM_PASS | sudo -S -k mv -v /home/$SERVER_NAME/tmp/* /var/www/apidocs/"