package loadero.model;

public enum LoaderoType {
    LOADERO_TEST_OPTIONS,
    LOADERO_GROUP,
    LOADERO_PARTICIPANT,
    LOADERO_RUN_INFO,
    LOADERO_SINGLE_RUN_RESULTS,
    LOADERO_SCRIPT_FILE_LOC,
    LOADERO_ALL_RUN_RESULTS
}
